version: '3'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    volumes:
      - jenkins_home:/var/jenkins_home
    ports:
      - "8080:8080"
    networks:
      - jenkins-network
    privileged: true  # Permite o acesso ao daemon do Docker no host
    environment:
      - DOCKER_HOST=tcp://host.docker.internal:2375  # Acesso ao daemon do Docker no host
    depends_on:
      - artifactory

  artifactory:
    image: docker.bintray.io/jfrog/artifactory-oss:latest
    container_name: artifactory
    ports:
      - "8082:8082"
    networks:
      - jenkins-network

networks:
  jenkins-network:
    driver: bridge

volumes:
  jenkins_home:
