pipeline {
    agent any

    environment {
        DOCKERHUB_USERNAME = credentials('dockerhub_username')
        DOCKERHUB_PASSWORD = credentials('dockerhub_password')
    }

    stages {
        stage('Download Jar from JFROG') {
            environment {
                JFROG_PASSWORD = credentials('token_jfrog')
            }
            steps {
                sh 'curl -u admin:$JFROG_PASSWORD -XGET http://artifactory:8082/artifactory/tema-final-1-job-1/Tema-final-1-0.0.1-SNAPSHOT.jar --output Tema-final-1-0.0.1-SNAPSHOT.jar'
            }
        }

        stage('Downloading Packer and Ansible Config Files') {
            steps {
                git branch: 'master', url: 'https://github.com/Brunna1989/tema-final-1.git'
            }
        }

        stage('Packer execution') {
            steps {
                sh 'apt-get update'
                sh 'packer init job-2/packer-configurations.hcl'
                sh 'packer build job-2/packer-configurations.hcl'
            }
        }

        stage('Push Docker Image') {
            steps {
                script {
                    def dockerhubCredentials = credentials('dockerhub_token') // Substitua pelo ID da credencial no Jenkins

                    withDockerServer([credentialsId: dockerhubCredentials]) {
                        // Faça o push da imagem para o Docker Hub
                        sh "docker push brunnadocker/tema-final-1-job-2:0.1"
                    }
                }
            }
        }
    }
}

