pipeline {
    agent any

    stages {
        stage('Pull Dockerhub') {
            steps {
                sh 'docker pull brunnadocker/brunna-dornelles-tema-final-1'
            }
        }
        stage('Docker run') {
            steps {
                sh 'docker run  -d -p 8085:8085 brunnadocker/brunna-dornelles-tema-final-1'
            }
        }
    }
}