pipeline {
    agent any

    stages {
        stage('Pull Dockerhub') {
            steps {
                sh 'docker pull brunnadocker/tema-final-1:0.1'
            }
        }
        stage('Docker run') {
            steps {
                sh 'docker run -d -p 8085:8085 brunnadocker/tema-final-1:0.1'
            }
        }
    }
}
